name: Docker Build Release Candidate
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]-rc[0-9][0-9]?'
  workflow_dispatch:
    inputs:
      rc-version:
        description: 'Docker image source release candidate version, ex: v1.0.0-rc0'
        required: true
        type: string
jobs:
  call-docker-image-rc:
    uses: ascendsoftware/gha-workflows/.github/workflows/docker-image-rc.yml@v2.0.0
    secrets: inherit
    with:
      aws-region: ${{ secrets.AWS_REGION_US_INFRASTRUCTURE_PROD }}
      ecr-registry: ${{ secrets.AWS_ECR_REPO_US_INFRASTRUCTURE_PROD }}
      ecr-repository: 'grafana-backup'
      dockerfile-path: './Dockerfile'
      rc-version: ${{ inputs.rc-version }}